In [1]:
import pandas as pd

In [22]:
df=pd.read_csv('jaipur_data.csv')

In [23]:
df

,id,m_id,client_m_id,hl_id,state,district,rural,stratum_code,psu_id,m_serial_no,...,housestatus,householdstatus,isheadchanged,fidh,fidx,as,wt,x,schedule_id,year
0,163321,205.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100070153,115.0,...,Residential/partly residential,Household Continues in same house,No,8.120790e+13,NaN,NaN,100.122450,N,4,Second Updation Round
1,163313,41.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100068839,73.0,...,Residential/partly residential,Household Continues in same house,No,8.120750e+13,NaN,NaN,100.122450,N,4,Second Updation Round
2,163297,163.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100069751,5.0,...,Residential/partly residential,Household Continues in same house,No,8.120710e+13,NaN,NaN,100.122450,N,4,Second Updation Round
3,163289,217.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100069170,25.0,...,Residential/partly residential,Household Continues in same house,No,8.120650e+13,NaN,NaN,100.122450,N,4,Second Updation Round
4,163281,82.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100068866,118.0,...,Residential/partly residential,Household Continues in same house,No,8.120620e+13,NaN,NaN,100.122450,N,4,Second Updation Round
5,163273,31.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100070243,41.0,...,Residential/partly residential,Household Continues in same house,Yes,8.120600e+13,NaN,NaN,100.122450,N,4,Second Updation Round
6,163265,45.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100069296,92.0,...,Residential/partly residential,Household Continues in same house,No,8.120570e+13,NaN,NaN,100.122450,N,4,Second Updation Round
7,575923,NaN,NaN,19883.0,RAJASTHAN,JAIPUR,Urban,Urban,100069163,NaN,...,NaN,NaN,NaN,NaN,NaN,12,100.122450,N,4,Baseline
8,575907,617.0,256.0,19667.0,RAJASTHAN,JAIPUR,Rural,population>=2000,100069105,353.0,...,NaN,NaN,NaN,NaN,NaN,-4,64.294121,N,4,Baseline
9,575915,622.0,136.0,19747.0,RAJASTHAN,JAIPUR,Urban,Urban,100069165,63.0,...,NaN,NaN,NaN,NaN,NaN,4.,100.122450,N,4,Baseline
10,575891,NaN,NaN,19383.0,RAJASTHAN,JAIPUR,Rural,population>=2000,100069101,NaN,...,NaN,NaN,NaN,NaN,NaN,-3,64.294121,N,4,Baseline
11,575883,NaN,NaN,19325.0,RAJASTHAN,JAIPUR,Rural,population>=2000,100069089,NaN,...,NaN,NaN,NaN,NaN,NaN,1.,64.294121,N,4,Baseline
12,575899,607.0,246.0,19535.0,RAJASTHAN,JAIPUR,Rural,population>=2000,100069087,232.0,...,NaN,NaN,NaN,NaN,NaN,-.,64.294121,N,4,Baseline
13,575867,592.0,139.0,19008.0,RAJASTHAN,JAIPUR,Urban,Urban,100070177,27.0,...,NaN,NaN,NaN,NaN,NaN,16,100.122450,N,4,Baseline
14,575875,599.0,133.0,19159.0,RAJASTHAN,JAIPUR,Urban,Urban,100069950,8.0,...,NaN,NaN,NaN,NaN,NaN,7.,100.122450,N,4,Baseline
15,575851,NaN,NaN,18844.0,RAJASTHAN,JAIPUR,Urban,Urban,100070164,NaN,...,NaN,NaN,NaN,NaN,NaN,7.,100.122450,N,4,Baseline
16,575859,588.0,136.0,18910.0,RAJASTHAN,JAIPUR,Urban,Urban,100069726,10.0,...,NaN,NaN,NaN,NaN,NaN,11,100.122450,N,4,Baseline
17,575835,584.0,167.0,18554.0,RAJASTHAN,JAIPUR,Urban,Urban,100070334,96.0,...,NaN,NaN,NaN,NaN,NaN,14,100.122450,N,4,Baseline
18,575843,NaN,NaN,18745.0,RAJASTHAN,JAIPUR,Urban,Urban,100070148,NaN,...,NaN,NaN,NaN,NaN,NaN,4.,100.122450,N,4,Baseline
19,575827,578.0,138.0,18392.0,RAJASTHAN,JAIPUR,Urban,Urban,100069850,47.0,...,NaN,NaN,NaN,NaN,NaN,12,100.122450,N,4,Baseline
20,575811,568.0,133.0,18141.0,RAJASTHAN,JAIPUR,Urban,Urban,100068834,96.0,...,NaN,NaN,NaN,NaN,NaN,4.,100.122450,N,4,Baseline
21,575819,NaN,NaN,18297.0,RAJASTHAN,JAIPUR,Urban,Urban,100068727,NaN,...,NaN,NaN,NaN,NaN,NaN,11,100.122450,N,4,Baseline
22,575795,NaN,NaN,17659.0,RAJASTHAN,JAIPUR,Urban,Urban,100068934,NaN,...,NaN,NaN,NaN,NaN,NaN,8.,100.122450,N,4,Baseline
23,575803,NaN,NaN,17898.0,RAJASTHAN,JAIPUR,Urban,Urban,100069052,NaN,...,NaN,NaN,NaN,NaN,NaN,9.,100.122450,N,4,Baseline
24,575779,552.0,134.0,17198.0,RAJASTHAN,JAIPUR,Urban,Urban,100069756,46.0,...,NaN,NaN,NaN,NaN,NaN,9.,100.122450,N,4,Baseline
25,575771,549.0,142.0,16975.0,RAJASTHAN,JAIPUR,Urban,Urban,100068961,222.0,...,NaN,NaN,NaN,NaN,NaN,1.,100.122450,N,4,Baseline
26,575787,NaN,NaN,17428.0,RAJASTHAN,JAIPUR,Urban,Urban,100070380,NaN,...,NaN,NaN,NaN,NaN,NaN,16,100.122450,N,4,Baseline
27,575763,NaN,NaN,16809.0,RAJASTHAN,JAIPUR,Urban,Urban,100068966,NaN,...,NaN,NaN,NaN,NaN,NaN,9.,100.122450,N,4,Baseline
28,575747,NaN,NaN,16606.0,RAJASTHAN,JAIPUR,Urban,Urban,100070134,NaN,...,NaN,NaN,NaN,NaN,NaN,13,100.122450,N,4,Baseline
29,575755,NaN,NaN,16704.0,RAJASTHAN,JAIPUR,Urban,Urban,100070139,NaN,...,NaN,NaN,NaN,NaN,NaN,6.,100.122450,N,4,Baseline
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1840,610544,203.0,NaN,NaN,RAJASTHAN,JAIPUR,Rural,population>=2000,100070206,15.0,...,Residential/partly residential,Household Continues in same house,No,8.120190e+13,NaN,NaN,64.294121,N,4,First Updation Round
1841,610552,261.0,NaN,NaN,RAJASTHAN,JAIPUR,Rural,population>=2000,100069099,89.0,...,Residential/partly residential,Household Continues in same house,No,8.120200e+13,NaN,NaN,64.294121,N,4,First Updation Round
1842,610560,217.0,NaN,NaN,RAJASTHAN,JAIPUR,Rural,population>=2000,100069492,58.0,...,Residential/partly residential,Household Continues in same house,No,8.120210e+13,NaN,NaN,64.294121,N,4,First Updation Round
1843,610568,117.0,NaN,NaN,RAJASTHAN,JAIPUR,Rural,population>=2000,100068750,93.0,...,Residential/partly residential,Household Continues in same house,No,8.120220e+13,NaN,NaN,64.294121,N,4,First Updation Round
1844,610576,321.0,NaN,NaN,RAJASTHAN,JAIPUR,Rural,population>=2000,100069608,76.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,4,First Updation Round
1845,610584,101.0,NaN,NaN,RAJASTHAN,JAIPUR,Rural,population>=2000,100069646,420.0,...,Residential/partly residential,Household Continues in same house,Yes,8.120240e+13,NaN,NaN,64.294121,N,4,First Updation Round
1846,610600,148.0,NaN,NaN,RAJASTHAN,JAIPUR,Rural,population>=2000,100070315,169.0,...,Residential/partly residential,Household Continues in same house,Yes,8.120270e+13,NaN,NaN,64.294121,N,4,First Updation Round
1847,610608,328.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100069733,135.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,4,First Updation Round
1848,610616,187.0,NaN,NaN,RAJASTHAN,JAIPUR,Rural,population>=2000,100069983,118.0,...,Residential/partly residential,Household Continues in same house,Yes,8.120290e+13,NaN,NaN,64.294121,N,4,First Updation Round
1849,610624,323.0,NaN,NaN,RAJASTHAN,JAIPUR,Rural,population>=2000,100070044,158.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,4,First Updation Round
1850,610632,235.0,NaN,NaN,RAJASTHAN,JAIPUR,Rural,population>=2000,100069375,63.0,...,Residential/partly residential,Household Continues in same house,No,8.120310e+13,NaN,NaN,64.294121,N,4,First Updation Round
1851,610640,89.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100070466,151.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,4,First Updation Round
1852,610648,78.0,NaN,NaN,RAJASTHAN,JAIPUR,Rural,population>=2000,100070057,234.0,...,Residential/partly residential,Household Continues in same house,No,8.120331e+13,NaN,NaN,64.294121,N,4,First Updation Round
1853,610656,350.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100070128,65.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,4,First Updation Round
1854,610664,12.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100069814,15.0,...,Residential/partly residential,Household Continues in same house,No,8.120390e+13,NaN,NaN,100.122450,N,4,First Updation Round
1855,610672,346.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100070242,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,4,First Updation Round
1856,610680,34.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100069555,52.0,...,Residential/partly residential,Household Continues in same house,No,8.120430e+13,NaN,NaN,100.122450,N,4,First Updation Round
1857,610688,87.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100069024,52.0,...,Residential/partly residential,Household Continues in same house,No,8.120450e+13,NaN,NaN,100.122450,N,4,First Updation Round
1858,610696,277.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100068884,25.0,...,Residential/partly residential,Household Continues in same house,No,8.120480e+13,NaN,NaN,100.122450,N,4,First Updation Round
1859,610704,17.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100070513,55.0,...,Residential/partly residential,Household Continues in same house,No,8.120500e+13,NaN,NaN,100.122450,N,4,First Updation Round
1860,610712,40.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100068701,87.0,...,Residential/partly residential,Household Continues in same house,No,8.120530e+13,NaN,NaN,100.122450,N,4,First Updation Round
1861,610720,9.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100070359,27.0,...,Residential/partly residential,Household Continues in same house,No,8.120540e+13,NaN,NaN,100.122450,N,4,First Updation Round
1862,610728,145.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100069287,104.0,...,Residential/partly residential,Household Continues in same house,No,8.120570e+13,NaN,NaN,100.122450,N,4,First Updation Round
1863,610736,238.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100070253,104.0,...,Residential/partly residential,Household Continues in same house,No,8.120600e+13,NaN,NaN,100.122450,N,4,First Updation Round
1864,610744,151.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100069179,3.0,...,Residential/partly residential,Household Continues in same house,No,8.120650e+13,NaN,NaN,100.122450,N,4,First Updation Round
1865,610752,351.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100068950,96.0,...,Residential/partly residential,Household Continues in same house,No,8.120680e+13,NaN,NaN,100.122450,N,4,First Updation Round
1866,610760,357.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100070386,49.0,...,Residential/partly residential,Household Continues in same house,No,8.120720e+13,NaN,NaN,100.122450,N,4,First Updation Round
1867,610768,154.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100068730,42.0,...,Residential/partly residential,Household Continues in same house,No,8.120760e+13,NaN,NaN,100.122450,N,4,First Updation Round
1868,610776,95.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100070335,147.0,...,Residential/partly residential,Household Continues in same house,No,8.120780e+13,NaN,NaN,100.122450,N,4,First Updation Round
1869,610784,369.0,NaN,NaN,RAJASTHAN,JAIPUR,Urban,Urban,100070181,67.0,...,Residential/partly residential,Household Continues in same house,No,8.120810e+13,NaN,NaN,100.122450,N,4,First Updation Round

In [24]:
df=df[['state','district','deceased_sex','month_of_death','year_of_death','death_symptoms','is_death_associated_with_preg','marital_status','highest_qualification','drinking_water_source','toilet_used']]

In [25]:
df

,state,district,deceased_sex,month_of_death,year_of_death,death_symptoms,is_death_associated_with_preg,marital_status,highest_qualification,drinking_water_source,toilet_used
0,RAJASTHAN,JAIPUR,Female,10,2011,NaN,No,Married and Gauna performed,Literate With formal education-Post Grad/ M.Te...,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
1,RAJASTHAN,JAIPUR,Male,6,2011,NaN,NaN,Married and Gauna performed,Literate with formal education-Graduate/B.Tech...,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
2,RAJASTHAN,JAIPUR,Male,11,2011,NaN,NaN,Married and Gauna performed,Literate With formal education-Middle,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
3,RAJASTHAN,JAIPUR,Female,3,2011,Hypothermia,NaN,Married and Gauna performed,Literate With formal education-Secondary/Matri...,Piped water into dwelling/yard/plot,"open defecation(field, brush,jungle etc.)"
4,RAJASTHAN,JAIPUR,Female,8,2011,NaN,NaN,Married and Gauna performed,Literate With formal education-Below primary,Public tap/standpipe,To septic tank
5,RAJASTHAN,JAIPUR,Male,12,2011,NaN,NaN,Widow/Widower,Literate With formal education-Middle,NaN,NaN
6,RAJASTHAN,JAIPUR,Female,11,2011,NaN,NaN,Married and Gauna performed,Literate With formal education-Post Grad/ M.Te...,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
7,RAJASTHAN,JAIPUR,Female,11,2009,NaN,No,Married and Gauna performed,Literate with formal education-Graduate/B.Tech...,Piped water into dwelling/yard/plot,To septic tank
8,RAJASTHAN,JAIPUR,Female,3,2009,NaN,0,Married and Gauna performed,Literate Without formal education,Tube well or Borehole,"open defecation(field, brush,jungle etc.)"
9,RAJASTHAN,JAIPUR,Female,8,2007,NaN,No,Married and Gauna performed,Literate Without formal education,Piped water into dwelling/yard/plot,"open defecation(field, brush,jungle etc.)"
10,RAJASTHAN,JAIPUR,Female,10,2007,NaN,NaN,Married and Gauna performed,Literate With formal education-Middle,Hand pump,"open defecation(field, brush,jungle etc.)"
11,RAJASTHAN,JAIPUR,Female,1,2007,Fever with Jaundice,NaN,Married and Gauna performed,Literate With formal education-Secondary/Matri...,Unprotected dug well,"open defecation(field, brush,jungle etc.)"
12,RAJASTHAN,JAIPUR,Male,8,2009,NaN,0,Married and Gauna performed,Literate With formal education-Secondary/Matri...,Tube well or Borehole,"open defecation(field, brush,jungle etc.)"
13,RAJASTHAN,JAIPUR,Male,2,2009,NaN,0,Married and Gauna performed,Literate with formal education-Graduate/B.Tech...,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
14,RAJASTHAN,JAIPUR,Female,12,2008,NaN,0,Widow/Widower,Literate With formal education-Primary,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
15,RAJASTHAN,JAIPUR,Male,3,2009,NaN,NaN,Married and Gauna performed,Literate with formal education-Graduate/B.Tech...,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
16,RAJASTHAN,JAIPUR,Female,3,2009,NaN,0,Married and Gauna performed,Literate with formal education-Graduate/B.Tech...,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
17,RAJASTHAN,JAIPUR,Male,2,2008,NaN,0,Widow/Widower,Literate With formal education-Below primary,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
18,RAJASTHAN,JAIPUR,Female,2,2008,NaN,NaN,Married and Gauna performed,Literate With formal education-Secondary/Matri...,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
19,RAJASTHAN,JAIPUR,Male,6,2007,NaN,0,Married and Gauna performed,Literate with formal education-Graduate/B.Tech...,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
20,RAJASTHAN,JAIPUR,Male,7,2008,NaN,0,Widow/Widower,Literate With formal education-Secondary/Matri...,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
21,RAJASTHAN,JAIPUR,Male,12,2008,NaN,0,Married and Gauna performed,Literate With formal education-Post Grad/ M.Te...,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
22,RAJASTHAN,JAIPUR,Male,5,2008,NaN,NaN,Married and Gauna performed,Literate Without formal education,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
23,RAJASTHAN,JAIPUR,Female,7,2008,NaN,NaN,Married and Gauna performed,Literate With formal education-Hr. Secondary/S...,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
24,RAJASTHAN,JAIPUR,Male,11,2007,NaN,0,Never married,Illiterate,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
25,RAJASTHAN,JAIPUR,Female,3,2008,NaN,0,Married and Gauna performed,Literate With formal education-Primary,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
26,RAJASTHAN,JAIPUR,Male,10,2008,Others,NaN,Married and Gauna performed,Literate With formal education-Secondary/Matri...,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
27,RAJASTHAN,JAIPUR,Female,1,2009,NaN,NaN,Married and Gauna performed,Literate with formal education-Graduate/B.Tech...,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
28,RAJASTHAN,JAIPUR,Female,1,2009,NaN,NaN,Married and Gauna performed,Literate With formal education-Secondary/Matri...,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
29,RAJASTHAN,JAIPUR,Male,5,2009,NaN,NaN,Married and Gauna performed,Literate With formal education-Secondary/Matri...,Tube well or Borehole,Flush/Pour flush latrine connected:-To piped s...
...,...,...,...,...,...,...,...,...,...,...,...
1840,RAJASTHAN,JAIPUR,Male,9,2010,NaN,NaN,Widow/Widower,Literate With formal education-Secondary/Matri...,Hand pump,"open defecation(field, brush,jungle etc.)"
1841,RAJASTHAN,JAIPUR,Female,9,2010,NaN,NaN,Married and Gauna performed,Literate With formal education-Primary,Tube well or Borehole,"open defecation(field, brush,jungle etc.)"
1842,RAJASTHAN,JAIPUR,Male,9,2010,NaN,NaN,Widow/Widower,Illiterate,Tube well or Borehole,Flush/Pour flush latrine connected:-To piped s...
1843,RAJASTHAN,JAIPUR,Male,12,2010,NaN,NaN,Married and Gauna performed,Illiterate,Tube well or Borehole,"open defecation(field, brush,jungle etc.)"
1844,RAJASTHAN,JAIPUR,Female,6,2010,Others,NaN,NaN,NaN,NaN,NaN
1845,RAJASTHAN,JAIPUR,Male,7,2010,Jaundice,NaN,Widow/Widower,Illiterate,Piped water into dwelling/yard/plot,To pit latrine
1846,RAJASTHAN,JAIPUR,Male,12,2010,NaN,NaN,Widow/Widower,Literate With formal education-Below primary,Piped water into dwelling/yard/plot,To pit latrine
1847,RAJASTHAN,JAIPUR,Male,12,2010,Convulsions soon after birth,NaN,NaN,NaN,NaN,NaN
1848,RAJASTHAN,JAIPUR,Male,7,2010,NaN,NaN,Widow/Widower,Literate Without formal education,Piped water into dwelling/yard/plot,To pit latrine
1849,RAJASTHAN,JAIPUR,Female,9,2010,Hypothermia,NaN,NaN,NaN,NaN,NaN
1850,RAJASTHAN,JAIPUR,Male,6,2010,Others,NaN,Married and Gauna performed,Literate With formal education-Middle,Hand pump,"open defecation(field, brush,jungle etc.)"
1851,RAJASTHAN,JAIPUR,Male,1,2010,NaN,NaN,NaN,NaN,NaN,NaN
1852,RAJASTHAN,JAIPUR,Female,12,2010,NaN,NaN,Married and Gauna performed,Illiterate,Hand pump,"open defecation(field, brush,jungle etc.)"
1853,RAJASTHAN,JAIPUR,Female,8,2010,NaN,NaN,NaN,NaN,NaN,NaN
1854,RAJASTHAN,JAIPUR,Male,2,2010,NaN,NaN,Married and Gauna performed,Literate With formal education-Primary,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
1855,RAJASTHAN,JAIPUR,Male,10,2010,NaN,NaN,NaN,NaN,NaN,NaN
1856,RAJASTHAN,JAIPUR,Male,12,2010,NaN,NaN,Married and Gauna performed,Literate With formal education-Below primary,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
1857,RAJASTHAN,JAIPUR,Male,12,2010,NaN,NaN,Married and Gauna performed,Literate With formal education-Primary,Public tap/standpipe,Flush/Pour flush latrine connected:-To piped s...
1858,RAJASTHAN,JAIPUR,Male,0,2010,NaN,NaN,Married and Gauna performed,Illiterate,Tanker /truck/Cart with Surface watersmall tank,Flush/Pour flush latrine connected:-To piped s...
1859,RAJASTHAN,JAIPUR,Female,11,2010,Diarrhoea / Dysentery,NaN,Married and Gauna performed,Literate With formal education-Secondary/Matri...,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
1860,RAJASTHAN,JAIPUR,Male,11,2010,NaN,NaN,Widow/Widower,Literate Without formal education,Piped water into dwelling/yard/plot,To septic tank
1861,RAJASTHAN,JAIPUR,Female,4,2010,Asphyxia,NaN,Married and Gauna performed,Literate With formal education-Post Grad/ M.Te...,Piped water into dwelling/yard/plot,To septic tank
1862,RAJASTHAN,JAIPUR,Female,6,2010,NaN,NaN,Widow/Widower,Literate with formal education-Graduate/B.Tech...,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
1863,RAJASTHAN,JAIPUR,Male,6,2010,Birth injuries,NaN,Widow/Widower,Literate Without formal education,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
1864,RAJASTHAN,JAIPUR,Male,11,2010,NaN,NaN,Married and Gauna performed,Literate With formal education-Primary,Public tap/standpipe,"open defecation(field, brush,jungle etc.)"
1865,RAJASTHAN,JAIPUR,Female,10,2010,NaN,NaN,Married and Gauna performed,Literate With formal education-Secondary/Matri...,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
1866,RAJASTHAN,JAIPUR,Female,10,2010,NaN,NaN,Married and Gauna performed,Literate With formal education-Primary,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
1867,RAJASTHAN,JAIPUR,Female,8,2010,NaN,NaN,Married and Gauna performed,Literate With formal education-Hr. Secondary/S...,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
1868,RAJASTHAN,JAIPUR,Male,8,2010,Birth injuries,NaN,Widow/Widower,Literate Without formal education,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...
1869,RAJASTHAN,JAIPUR,Male,7,2010,NaN,NaN,Married and Gauna performed,Literate with formal education-Graduate/B.Tech...,Piped water into dwelling/yard/plot,Flush/Pour flush latrine connected:-To piped s...

In [26]:
df.to_csv('Filtered_data.csv')